In [1]:
import numpy  as np

In [26]:
a = np.arange(8).reshape(2,4)+ 10 
np.argmin(a,axis=1)

array([0, 0], dtype=int64)

In [25]:
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [17]:
b= np.arange(6)+10
np.expand_dims(b,axis=1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [23]:
a

array([[10, 11, 12],
       [13, 14, 15]])

In [31]:
a = np.arange(10)
np.where(a%2 ==0, 'hey',a)

array(['hey', '1', 'hey', '3', 'hey', '5', 'hey', '7', 'hey', '9'],
      dtype='<U11')

In [30]:
10%2== 

0

In [32]:
x, y = np.ogrid[:3, :4]
y

array([[0, 1, 2, 3]])